export const START_FETCHING_ORDERPENDING =
  'redux/OrderPending/START_FETCHING_ORDERPENDING';
export const SUCCESS_FETCHING_ORDERPENDING =
  'redux/OrderPending/SUCCESS_FETCHING_ORDERPENDING';
export const ERROR_FETCHING_ORDERPENDING =
  'redux/OrderPending/ERROR_FETCHING_ORDERPENDING';
